---
- name: Allowed Network
  blockinfile:
    path: /etc/squid/allowed_ips.txt
    create: yes
    block: |
      {{ interface_ipv4 }}
      {{ interface_ipv6 }}

- name: Configure Squid
  template:
    src: squid.conf.j2
    dest: /etc/squid/squid.conf
    owner: root
    group: root
    mode: "0640"
    backup: yes
  notify: Start and Enable squid
