---
- name: Create IPv6 Configuration
  template:
    src: dhcpd6.conf.j2
    dest: /etc/dhcp/dhcpd6.conf
    owner: root
    group: root
    mode: "0644"
    backup: yes

- name: Check dhcpd6 configuration
  shell: dhcpd -6 -t
  notify: Restart dhcpd6

- name: Configure Radvd
  template:
    src: radvd.conf.j2
    dest: /etc/radvd.conf
    owner: root
    group: root
    mode: "0644"
    backup: yes
  notify: Restart radvd
