- name: Deploy zabbix with Docker
  hosts: physical
  gather_facts: False

  vars:
    # srv_DOCKER: "/srv/DOCKER"
    # search_domain: "local.lab"
    cert_definition: "{{ zabbix_ssl }}"

  vars_prompt:
    - name: "ca_certificate_passphrase"
      prompt: "CA Certificate Passphrase"
      private: yes

  tasks:
    - name: Install dependencies
      package:
        name:
          - python-pip
        state: present

    - name: Install Python Docker
      shell: "pip install docker"

    - name: Create `{{ srv_DOCKER }}/volumes/zabbix` Directory
      file:
        path: "{{ srv_DOCKER }}/volumes/zabbix"
        state: directory

    - name: Copy `Zabbix` Application
      copy:
        src: ./zabbix/
        dest: "{{ srv_DOCKER }}/volumes/zabbix/"

    - name: launch the docker-compose
      shell: "docker-compose up -d"
      args:
        chdir: "{{ srv_DOCKER }}/volumes/zabbix/"

    - firewalld:
        zone: public
        port: 8081/tcp
        permanent: yes
        immediate: yes
        state: enabled

    - firewalld:
        zone: public
        port: 8443/tcp
        permanent: yes
        immediate: yes
        state: enabled

    - firewalld:
        zone: public
        port: 10050/tcp
        permanent: yes
        immediate: yes
        state: enabled

    - firewalld:
        zone: public
        port: 10051/tcp
        permanent: yes
        immediate: yes
        state: enabled

    - name: Allow Nginx to listen on tcp port 8081
      seport:
        ports: 8081
        proto: tcp
        setype: http_port_t
        state: present

    - name: Allow Nginx to listen on tcp port 8443
      seport:
        ports: 8443
        proto: tcp
        setype: http_port_t
        state: present

    - name: Create log directory
      file:
        path: /var/log/nginx/zabbix
        state: directory

    - name: generate SSL (zabbix.crt & zabbix.key)
      include_role:
        name: ../roles/generateCertificate

    - name: Attach Proxy
      template:
        src: "./reverse_proxy/zabbix.conf.j2"
        dest: "/etc/nginx/conf.d/zabbix.conf"
        owner: root
        group: root
        mode: "0644"
        backup: yes

    - name: Reload nginx to apply changes
      systemd:
        name: nginx
        state: reloaded
