- name: Deploy Next Cloud with Docker
  hosts: physical
  gather_facts: no

  vars:
    srv_DOCKER: "/srv/DOCKER"
    search_domain: "local.lab"

  tasks:
    - name: Install dependencies
      package:
        name:
          - python-pip
        state: present

    - name: Install Python Docker
      shell: "pip install docker"

    - name: Create `{{ srv_DOCKER }}/volumes/nextcloud` Directory
      file:
        path: "{{ srv_DOCKER }}/volumes/nextcloud"
        state: directory

    - name: Create `{{ srv_DOCKER }}/volumes/nextcloud/share` Directory
      file:
        path: "{{ srv_DOCKER }}/volumes/nextcloud/share"
        state: directory

    - name: Deploy nextcloud with Docker
      docker_container:
        name: Nextcloud
        image: nextcloud
        state: started
        recreate: true
        restart_policy: always
        volumes:
          - "{{ srv_DOCKER }}/volumes/nextcloud:/var/www/html"
          - "{{ srv_DOCKER }}/volumes/nextcloud/share:/srv/share"
        ports:
          - "9090:80"

    - firewalld:
        zone: public
        port: 9090/tcp
        permanent: yes
        immediate: yes
        state: enabled

    - name: Allow Nginx to listen on tcp port 9090
      seport:
        ports: 9090
        proto: tcp
        setype: http_port_t
        state: present

    - name: Create log directory
      file:
        path: /var/log/nginx/nextcloud
        state: directory

    - set_fact:
        cert_name: "box"
        ca_certificate_name: "local_CA"
        alt_name: "box.local.lab"

    - name: generate SSL (box.crt & box.key)
      import_tasks: ../tasks/generate_ssl.yml

    - name: Attach Proxy
      template:
        src: "./reverse_proxy/nextcloud.conf.j2"
        dest: "/etc/nginx/conf.d/nextcloud.conf"
        owner: root
        group: root
        mode: "0644"
        backup: yes

    - name: Reload nginx to apply changes
      systemd:
        name: nginx
        state: reloaded
