- name: Deploy Registry HTTP with Docker
  hosts: physical
  gather_facts: no

  vars:
    # srv_DOCKER: "/srv/DOCKER"
    # search_domain: "local.lab"
    cert_definition: "{{ registry_ssl }}"

  vars_prompt:
    - name: "ca_certificate_passphrase"
      prompt: "CA Certificate Passphrase"
      private: yes

  tasks:
    - name: Install dependencies
      package:
        name:
          - python-pip
        state: present

    - name: Install Python Docker
      shell: "pip install docker"

    - name: Create `Registry` Directory
      file:
        path: "{{ srv_DOCKER }}/volumes/registry"
        state: directory

    - name: Deploy `Registry` with Docker
      docker_container:
        name: Registry
        image: registry:2
        state: started
        recreate: true
        restart_policy: always
        volumes:
          - "{{ srv_DOCKER }}/volumes/registry:/var/lib/registry"
        ports:
          - "5000:5000"

    - firewalld:
        zone: public
        port: 5000/tcp
        permanent: yes
        immediate: yes
        state: enabled

    - name: Allow Nginx to listen on tcp port 5000
      seport:
        ports: 5000
        proto: tcp
        setype: http_port_t
        state: present

    - name: Create log directory
      file:
        path: /var/log/nginx/registry
        state: directory

    - name: generate SSL (registry.crt & registry.key)
      include_role:
        name: ../roles/generateCertificate

    - name: Attach Proxy
      template:
        src: "./reverse_proxy/registry.conf.j2"
        dest: "/etc/nginx/conf.d/registry.conf"
        owner: root
        group: root
        mode: "0644"
        backup: yes

    - name: Reload nginx to apply changes
      systemd:
        name: nginx
        state: reloaded
