- name: Deploy Portainer with Docker
  hosts: physical
  gather_facts: no

  vars:
    srv_DOCKER: "/srv/DOCKER"
    search_domain: "local.lab"

  tasks:
    - name: Install dependencies
      package:
        name:
          - python-pip
        state: present

    - name: Install Python Docker
      shell: "pip install docker"

    - name: Create `{{ srv_DOCKER }}/volumes/portainer` Directory
      file:
        path: "{{ srv_DOCKER }}/volumes/portainer"
        state: directory

    - name: Create `{{ srv_DOCKER }}/volumes/portainer/data` Directory
      file:
        path: "{{ srv_DOCKER }}/volumes/portainer/data"
        state: directory

    - name: Deploy portainer with Docker
      docker_container:
        name: Portainer
        image: portainer/portainer
        state: started
        recreate: true
        restart_policy: always
        volumes:
          - "/var/run/docker.sock:/var/run/docker.sock"
          - "{{ srv_DOCKER }}/volumes/portainer/data:/data"
        ports:
          - "9000:9000"
          - "8000:8000"

    - firewalld:
        zone: public
        port: 9000/tcp
        permanent: yes
        immediate: yes
        state: enabled

    - firewalld:
        zone: public
        port: 8000/tcp
        permanent: yes
        immediate: yes
        state: enabled

    - name: Allow Nginx to listen on tcp port 9000
      seport:
        ports: 9000
        proto: tcp
        setype: http_port_t
        state: present

    - name: Create log directory
      file:
        path: /var/log/nginx/portainer
        state: directory

    - set_fact:
        cert_name: "portainer"
        ca_certificate_name: "local_CA"
        alt_name: "portainer.local.lab"

    - name: generate SSL (portainer.crt & portainer.key)
      import_tasks: ../tasks/generate_ssl.yml

    - name: Attach Proxy
      template:
        src: "./reverse_proxy/portainer.conf.j2"
        dest: "/etc/nginx/conf.d/portainer.conf"
        owner: root
        group: root
        mode: "0644"
        backup: yes

    - name: Reload nginx to apply changes
      systemd:
        name: nginx
        state: reloaded
