# Install CLI tool : brew install iron-functions
# Or : curl -LSs git.io/ironfn | sh

- name: Deploy Iron Functions UI with Docker
  hosts: physical
  gather_facts: no

  vars:
    # srv_DOCKER: "/srv/DOCKER"
    # search_domain: "local.lab"
    cert_definition: "{{ ironFunctionUI_ssl }}"

  vars_prompt:
    - name: "ca_certificate_passphrase"
      prompt: "CA Certificate Passphrase"
      private: yes

  tasks:
    - name: Install dependencies
      package:
        name:
          - python-pip
        state: present

    - name: Install or upgrade Python Docker
      shell: "pip install --upgrade docker"

    - name: Deploy `Iron Functions UI` with Docker
      docker_container:
        name: IronFunctionsUI
        image: iron/functions-ui:0.0.2
        state: started
        recreate: true
        restart_policy: always
        links: 
          - IronFunctions:api
        env:
          API_URL: http://api:8080
        ports:
          - "4000:4000"

    - firewalld:
        zone: public
        port: 4000/tcp
        permanent: yes
        immediate: yes
        state: enabled

    - name: Allow Nginx to listen on tcp port 4000
      seport:
        ports: 4000
        proto: tcp
        setype: http_port_t
        state: present

    - name: Create log directory
      file:
        path: /var/log/nginx/functionsui
        state: directory

    - name: generate SSL (functionsUI.crt & functionsUI.key)
      include_role:
        name: ../roles/generateCertificate

    - name: Attach Proxy
      template:
        src: "./reverse_proxy/functionsUI.conf.j2"
        dest: "/etc/nginx/conf.d/functionsUI.conf"
        owner: root
        group: root
        mode: "0644"
        backup: yes

    - name: Reload nginx to apply changes
      systemd:
        name: nginx
        state: reloaded
