- name: Deploy Minio with Docker
  hosts: physical
  gather_facts: no

  vars:
    srv_DOCKER: "/srv/DOCKER"
    search_domain: "local.lab"

  vars_prompt:
    - name: access_key
      prompt: "Access Key"
      private: no
    - name: secret_key
      prompt: "Secret Key"
      private: yes

  tasks:
    - name: Install dependencies
      package:
        name:
          - python-pip
        state: present

    - name: Install or upgrade Python Docker
      shell: "pip install --upgrade docker"

    - name: Create `Minio` Directory
      file:
        path: "{{ srv_DOCKER }}/volumes/minio"
        state: directory

    - name: Deploy `Minio` with Docker
      docker_container:
        name: Minio
        image: minio/minio
        state: started
        recreate: true
        restart_policy: always
        command: server /data
        env:
          MINIO_ACCESS_KEY: "{{ access_key }}"
          MINIO_SECRET_KEY: "{{ secret_key }}"
        volumes:
          - "{{ srv_DOCKER }}/volumes/minio:/data"
        ports:
          - "9999:9000"

    - firewalld:
        zone: public
        port: 9999/tcp
        permanent: yes
        immediate: yes
        state: enabled

    - name: Allow Nginx to listen on tcp port 9999
      seport:
        ports: 9999
        proto: tcp
        setype: http_port_t
        state: present

    - name: Create log directory
      file:
        path: /var/log/nginx/minio
        state: directory

    - set_fact:
        cert_name: "minio"
        ca_certificate_name: "local_CA"
        alt_name: "minio.local.lab"

    - name: generate SSL (minio.crt & minio.key)
      import_tasks: ../tasks/generate_ssl.yml

    - name: Attach Proxy
      template:
        src: "./reverse_proxy/minio.conf.j2"
        dest: "/etc/nginx/conf.d/minio.conf"
        owner: root
        group: root
        mode: "0644"
        backup: yes

    - name: Reload nginx to apply changes
      systemd:
        name: nginx
        state: reloaded
