- name: Deploy PlantUML with Docker
  hosts: physical
  gather_facts: no

  vars:
    # srv_DOCKER: "/srv/DOCKER"
    # search_domain: "local.lab"
    cert_definition: "{{ plantuml_ssl }}"

  vars_prompt:
    - name: "ca_certificate_passphrase"
      prompt: "CA Certificate Passphrase"
      private: yes

  tasks:
    - name: Install dependencies
      package:
        name:
          - python-pip
        state: present

    - name: Install Python Docker
      shell: "pip install docker"

    - name: Deploy PlantUML with Docker
      docker_container:
        name: PlantUML
        image: plantuml/plantuml-server:jetty
        state: started
        recreate: true
        restart_policy: always
        ports:
          - "8082:8080"

    - firewalld:
        zone: public
        port: 8082/tcp
        permanent: yes
        immediate: yes
        state: enabled

    - name: Allow Nginx to listen on tcp port 8082
      seport:
        ports: 8082
        proto: tcp
        setype: http_port_t
        state: present

    - name: Create log directory
      file:
        path: /var/log/nginx/plantuml
        state: directory

    - name: generate SSL (plantuml.crt & plantuml.key)
      include_role:
        name: ../roles/generateCertificate

    - name: Attach Proxy
      template:
        src: "./reverse_proxy/plantuml.conf.j2"
        dest: "/etc/nginx/conf.d/plantuml.conf"
        owner: root
        group: root
        mode: "0644"
        backup: yes

    - name: Reload nginx to apply changes
      systemd:
        name: nginx
        state: reloaded
