# Install CLI tool : brew install iron-functions
# Or : curl -LSs git.io/ironfn | sh

- name: Deploy Iron Functions with Docker
  hosts: physical
  gather_facts: no

  vars:
    # srv_DOCKER: "/srv/DOCKER"
    # search_domain: "local.lab"
    cert_definition: "{{ ironFunction_ssl }}"

  vars_prompt:
    - name: "ca_certificate_passphrase"
      prompt: "CA Certificate Passphrase"
      private: yes

  tasks:
    - name: Install dependencies
      package:
        name:
          - python-pip
        state: present

    - name: Install or upgrade Python Docker
      shell: "pip install --upgrade docker"

    - name: Create `Iron Functions` Directory
      file:
        path: "{{ srv_DOCKER }}/volumes/ironFunctions"
        state: directory

    - name: Deploy `Iron Functions` with Docker
      docker_container:
        name: IronFunctions
        image: iron/functions
        state: started
        recreate: true
        restart_policy: always
        volumes:
          - "{{ srv_DOCKER }}/volumes/ironFunctions/data:/app/data"
          - /var/run/docker.sock:/var/run/docker.sock
        ports:
          - "8888:8080"

    - firewalld:
        zone: public
        port: 8888/tcp
        permanent: yes
        immediate: yes
        state: enabled

    - name: Allow Nginx to listen on tcp port 8888
      seport:
        ports: 8888
        proto: tcp
        setype: http_port_t
        state: present

    - name: Create log directory
      file:
        path: /var/log/nginx/functions
        state: directory

    - name: generate SSL (functions.crt & functions.key)
      include_role:
        name: ../roles/generateCertificate

    - name: Attach Proxy
      template:
        src: "./reverse_proxy/functions.conf.j2"
        dest: "/etc/nginx/conf.d/functions.conf"
        owner: root
        group: root
        mode: "0644"
        backup: yes

    - name: Reload nginx to apply changes
      systemd:
        name: nginx
        state: reloaded
