- name: Deploy Verdaccio with Docker
  hosts: physical
  gather_facts: no

  vars:
    # srv_DOCKER: "/srv/DOCKER"
    # search_domain: "local.lab"
    cert_definition: "{{ verdaccio_ssl }}"

  vars_prompt:
    - name: "ca_certificate_passphrase"
      prompt: "CA Certificate Passphrase"
      private: yes

  tasks:
    - name: Install dependencies
      package:
        name:
          - python-pip
        state: present

    - name: Install Python Docker
      shell: "pip install docker"

    - name: Create Verdaccio Directory
      file:
        path: "{{ srv_DOCKER }}/volumes/verdaccio"
        state: directory

    - name: Update `verdaccio` permissions
      shell: "chown -R 10001:65533 {{ srv_DOCKER }}/volumes/verdaccio/"

    - name: Copy `Verdaccio` project
      copy:
        src: "./verdaccio/"
        dest: "{{ srv_DOCKER }}/volumes/verdaccio/"

    - name: Copy `docker-compose`
      template:
        src: "./verdaccio/docker-compose.yml.j2"
        dest: "{{ srv_DOCKER }}/volumes/verdaccio/docker-compose.yml"
        owner: root
        group: root
        mode: "0644"
        backup: yes

    - name: launch `docker-compose`
      shell: "docker-compose up -d"
      args:
        chdir: "{{ srv_DOCKER }}/volumes/verdaccio/"

    - firewalld:
        zone: public
        port: 4873/tcp
        permanent: yes
        immediate: yes
        state: enabled

    - name: Allow Nginx to listen on tcp port 4873
      seport:
        ports: 4873
        proto: tcp
        setype: http_port_t
        state: present

    - name: Create log directory
      file:
        path: /var/log/nginx/verdaccio
        state: directory

    - name: generate SSL (npm.crt & npm.key)
      include_role:
        name: ../roles/generateCertificate

    - name: Attach Proxy
      template:
        src: "./reverse_proxy/verdaccio.conf.j2"
        dest: "/etc/nginx/conf.d/verdaccio.conf"
        owner: root
        group: root
        mode: "0644"
        backup: yes

    - name: Reload nginx to apply changes
      systemd:
        name: nginx
        state: reloaded

    - debug:
        msg: "Follow this documentation to add users and configure clients : https://verdaccio.org/docs/en/installation"
