---
- name: Create SSL directory
  file:
    path: /etc/nginx/ssl
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Authorize HTTP in firewall
  firewalld:
    zone: public
    service: http
    permanent: yes
    immediate: yes
    state: enabled

- name: Authorize HTTPS in firewall
  firewalld:
    zone: public
    service: https
    permanent: yes
    immediate: yes
    state: enabled
