- name: Install and Configure mail with sendgrid
  hosts: storage
  become: yes

  vars_prompt:
    - name: "sendgrid_password"
      prompt: "Sendgrid API Password"
      private: yes

  roles:
    - { role: ../../roles/mail }
