---
- name: Configure the shares
  template:
    src: "{{ template_samba }}"
    dest: /etc/samba/smb.conf
    owner: root
    group: root
    mode: "0644"
    backup: yes
  notify: Start and Enable smb
