---
# handlers file for configureBind9
- name: Start and Enable named
  service:
    name: named
    state: started
    enabled: yes

- name: Restart named
  service:
    name: named
    state: restarted
    enabled: yes
