version: "3.5"
services:
  zabbix-server:
    image: zabbix/zabbix-server-mysql:centos-5.0-latest
    restart: always
    ports:
      - "10051:10051"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /srv/DOCKER/volumes/zabbix/usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts:ro
      - /srv/DOCKER/volumes/zabbix/usr/lib/zabbix/externalscripts:/usr/lib/zabbix/externalscripts:ro
      - /srv/DOCKER/volumes/zabbix/var/lib/zabbix/export:/var/lib/zabbix/export:rw
      - /srv/DOCKER/volumes/zabbix/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
      - /srv/DOCKER/volumes/zabbix/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
      - /srv/DOCKER/volumes/zabbix/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
      - /srv/DOCKER/volumes/zabbix/var/lib/zabbix/mibs:/var/lib/zabbix/mibs:ro
      - /srv/DOCKER/volumes/zabbix/var/lib/zabbix/snmptraps:/var/lib/zabbix/snmptraps:ro
    links:
      - mysql-server:mysql-server
      - zabbix-java-gateway:zabbix-java-gateway
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    deploy:
      resources:
        limits:
          cpus: "0.70"
          memory: 1G
        reservations:
          cpus: "0.5"
          memory: 512M
    env_file:
      - .env_db_mysql
      - .env_srv
    secrets:
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
    #   - client-key.pem
    #   - client-cert.pem
    #   - root-ca.pem
    depends_on:
      - mysql-server
      - zabbix-java-gateway
      - zabbix-snmptraps
    networks:
      zbx_net_backend:
        aliases:
          - zabbix-server
          - zabbix-server-mysql
          - zabbix-server-centos-mysql
          - zabbix-server-mysql-centos
      zbx_net_frontend:
    #  devices:
    #   - "/dev/ttyUSB0:/dev/ttyUSB0"
    stop_grace_period: 30s
    sysctls:
      - net.ipv4.ip_local_port_range=1024 65000
      - net.ipv4.conf.all.accept_redirects=0
      - net.ipv4.conf.all.secure_redirects=0
      - net.ipv4.conf.all.send_redirects=0
    labels:
      com.zabbix.description: "Zabbix server with MySQL database support"
      com.zabbix.company: "Zabbix LLC"
      com.zabbix.component: "zabbix-server"
      com.zabbix.dbtype: "mysql"
      com.zabbix.os: "centos"

  zabbix-web-nginx-mysql:
    image: zabbix/zabbix-web-nginx-mysql:centos-5.0-latest
    restart: always
    ports:
      - "8081:8080"
      - "8443:8443"
    links:
      - mysql-server:mysql-server
      - zabbix-server:zabbix-server
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /srv/DOCKER/volumes/zabbix/etc/ssl/nginx:/etc/ssl/nginx:ro
      - /srv/DOCKER/volumes/zabbix/usr/share/zabbix/modules/:/usr/share/zabbix/modules/:ro
    deploy:
      resources:
        limits:
          cpus: "0.70"
          memory: 512M
        reservations:
          cpus: "0.5"
          memory: 256M
    env_file:
      - .env_db_mysql
      - .env_web
    secrets:
      - MYSQL_USER
      - MYSQL_PASSWORD
    #   - client-key.pem
    #   - client-cert.pem
    #   - root-ca.pem
    depends_on:
      - mysql-server
      - zabbix-server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      zbx_net_backend:
        aliases:
          - zabbix-web-nginx-mysql
          - zabbix-web-nginx-centos-mysql
          - zabbix-web-nginx-mysql-centos
      zbx_net_frontend:
    stop_grace_period: 10s
    sysctls:
      - net.core.somaxconn=65535
    labels:
      com.zabbix.description: "Zabbix frontend on Nginx web-server with MySQL database support"
      com.zabbix.company: "Zabbix LLC"
      com.zabbix.component: "zabbix-frontend"
      com.zabbix.webserver: "nginx"
      com.zabbix.dbtype: "mysql"
      com.zabbix.os: "centos"

  zabbix-agent:
    image: zabbix/zabbix-agent:centos-5.0-latest
    restart: always
    ports:
      - "10050:10050"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /srv/DOCKER/volumes/zabbix/etc/zabbix/zabbix_agentd.d:/etc/zabbix/zabbix_agentd.d:ro
      - /srv/DOCKER/volumes/zabbix/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
      - /srv/DOCKER/volumes/zabbix/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
      - /srv/DOCKER/volumes/zabbix/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
    links:
      - zabbix-server:zabbix-server
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 128M
        reservations:
          cpus: "0.1"
          memory: 64M
      mode: global
    env_file:
      - .env_agent
    privileged: true
    pid: "host"
    networks:
      zbx_net_backend:
        aliases:
          - zabbix-agent
          - zabbix-agent-passive
          - zabbix-agent-centos
      # zbx_net_frontend: To expose the agent to everyone ... please don't do that, configure the web interface properly instead
    stop_grace_period: 5s
    labels:
      com.zabbix.description: "Zabbix agent"
      com.zabbix.company: "Zabbix LLC"
      com.zabbix.component: "zabbix-agentd"
      com.zabbix.os: "centos"

  zabbix-java-gateway:
    image: zabbix/zabbix-java-gateway:centos-5.0-latest
    restart: always
    ports:
      - "10052:10052"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M
    env_file:
      - .env_java
    networks:
      zbx_net_backend:
        aliases:
          - zabbix-java-gateway
          - zabbix-java-gateway-centos
    stop_grace_period: 5s
    labels:
      com.zabbix.description: "Zabbix Java Gateway"
      com.zabbix.company: "Zabbix LLC"
      com.zabbix.component: "java-gateway"
      com.zabbix.os: "centos"

  zabbix-snmptraps:
    image: zabbix/zabbix-snmptraps:centos-5.0-latest
    restart: always
    ports:
      - "162:1162/udp"
    volumes:
      - /srv/DOCKER/volumes/zabbix/var/lib/zabbix/snmptraps:/var/lib/zabbix/snmptraps:rw
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
        reservations:
          cpus: "0.25"
          memory: 128M
    networks:
      zbx_net_frontend:
        aliases:
          - zabbix-snmptraps
      zbx_net_backend:
    stop_grace_period: 5s
    labels:
      com.zabbix.description: "Zabbix snmptraps"
      com.zabbix.company: "Zabbix LLC"
      com.zabbix.component: "snmptraps"
      com.zabbix.os: "ubuntu"

  mysql-server:
    image: mysql:8.0
    restart: always
    command:
      - mysqld
      - --character-set-server=utf8
      - --collation-server=utf8_bin
      - --default-authentication-plugin=mysql_native_password
    #   - --require-secure-transport
    #   - --ssl-ca=/run/secrets/root-ca.pem
    #   - --ssl-cert=/run/secrets/server-cert.pem
    #   - --ssl-key=/run/secrets/server-key.pem
    volumes:
      - /srv/DOCKER/volumes/zabbix/var/lib/mysql:/var/lib/mysql:rw
    env_file:
      - .env_db_mysql
    secrets:
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
    #   - server-key.pem
    #   - server-cert.pem
    #   - root-ca.pem
    stop_grace_period: 1m
    networks:
      zbx_net_backend:
        aliases:
          - mysql-server
          - zabbix-database
          - mysql-database

  db_data_mysql:
    image: busybox
    volumes:
      - /srv/DOCKER/volumes/zabbix/var/lib/mysql:/var/lib/mysql:rw

networks:
  zbx_net_frontend:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
  zbx_net_backend:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    internal: true
    ipam:
      driver: default
      config:
        - subnet: 172.16.239.0/24

secrets:
  MYSQL_USER:
    file: ./.MYSQL_USER
  MYSQL_PASSWORD:
    file: ./.MYSQL_PASSWORD
  MYSQL_ROOT_PASSWORD:
    file: ./.MYSQL_ROOT_PASSWORD
#  client-key.pem:
#    file: ./.ZBX_DB_KEY_FILE
#  client-cert.pem:
#    file: ./.ZBX_DB_CERT_FILE
#  root-ca.pem:
#    file: ./.ZBX_DB_CA_FILE
#  server-cert.pem:
#    file: ./.DB_CERT_FILE
#  server-key.pem:
#    file: ./.DB_KEY_FILE
