#
# This is the config file used for the docker images.
# It allows all users to do anything, so don't use it on production systems.
#
# Do not configure host and port under `listen` in this file
# as it will be ignored when using docker.
# see https://verdaccio.org/docs/en/docker#docker-and-custom-port-configuration
#
# Look here for more config file examples:
# https://github.com/verdaccio/verdaccio/tree/master/conf
#

# path to a directory with all packages
storage: /verdaccio/storage
# path to a directory with plugins to include
plugins: /verdaccio/plugins

web:
  # WebUI is enabled as default, if you want disable it, just uncomment this line
  #enable: false
  title: Studiowebux NPM
  scope: "@studiowebux"
  # logo: https://www.newsdogapp.com/static/img/logo@1x.c2757d.png
  primary_color: "#F4CB00"
  # comment out to disable gravatar support
  # gravatar: false
  # by default packages are ordercer ascendant (asc|desc)
  # sort_packages: asc

auth:
  htpasswd:
    file: /verdaccio/storage/htpasswd
    # Maximum amount of users allowed to register, defaults to "+infinity".
    # You can set this to -1 to disable registration.
    # max_users: 1000

# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
    cache: false
  yarnjs:
    url: https://registry.yarnpkg.com/
    cache: false
  cnpmjs:
    url: https://registry.npm.taobao.org/
    cache: false

packages:
  '@*/*':
    # scoped packages
    access: $all
    publish: $authenticated
    unpublish: $authenticated
    proxy: npmjs

  '@studiowebux/*':
    access: $all
    publish: $all
    unpublish: $all

  '**':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $all

    # allow all known users to publish/publish packages
    # (anyone can register by default, remember?)
    publish: $authenticated
    unpublish: $authenticated

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs

middlewares:
  audit:
    enabled: true

# log settings
logs:
  # - { type: stdout, format: pretty, level: http }
  # - { type: file, path: /verdaccio/logs/info.log, level: info }
  - {
      type: rotating-file,
      format: json,
      path: /verdaccio/logs/http.jsonl,
      level: http,
      options: { period: 1d, count: 30 },
    }
#experiments:
#  # support for npm token command
#  token: false

listen:
  # - localhost:4873            # default value
  # - http://localhost:4873     # same thing
  # - 0.0.0.0:4873              # listen on all addresses (INADDR_ANY)
  # - https://example.org:4873  # if you want to use https
  # - "[::1]:4873"                # ipv6
  # - unix:/tmp/verdaccio.sock    # unix socket