---
- name: Stop Docker service before
  systemd:
    name: docker
    state: stopped

- name: Move existant files to '{{ srv_DOCKER }}/data'
  shell: sudo rsync -aP /var/lib/docker/ {{ srv_DOCKER }}/data

# https://linuxconfig.org/how-to-move-docker-s-default-var-lib-docker-to-another-directory-on-ubuntu-debian-linux
- name: Configure docker data directory to `{{ srv_DOCKER }}/data` and configure the network
  lineinfile:
    path: /lib/systemd/system/docker.service
    regexp: "ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock"
    line: "ExecStart=/usr/bin/dockerd -g {{ srv_DOCKER }}/data -H fd:// --containerd=/run/containerd/containerd.sock {{ docker_network }}"

- name: Remove `/var/lib/docker`
  file:
    path: "/var/lib/docker/"
    state: absent
  notify: 
    - Reload Daemon
    - Start and Enable docker
