---
- name: Generate PFSense user certificate
  hosts: physical
  become: yes

  vars_prompt:
    - name: "ca_certificate_passphrase"
      prompt: "CA Certificate Passphrase"
      private: yes

  vars:
    cert_definition: "{{ pfsense_client }}"

  roles:
    - { role: roles/generateCertificate }
