---
# tasks file for exportNFS
- name: Create /etc/exports
  template:
    src: exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: "0644"
    backup: yes
  notify: 
    - Start and Enable nfs
    - Restart nfs
